### ISSUE TITLE
Compile time error after adding the library in a project

### ISSUE THREAD

**Issue by DivyaArora-24** [AmolBorse/angular4-multiselect-dropdown#1]
When I compile my project, I get the below error 

ERROR in ./node_modules/angular4-multiselect-dropdown/angular4-multiselect-dropdown.ts
Module build failed: Error: D:\Angular_Projects\MutipleSelectionDropdown\node_modules\angular4-multiselect-dropdown\angular4-multiselect-dropdown.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Angular_Projects\MutipleSelectionDropdown\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (D:\Angular_Projects\MutipleSelectionDropdown\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by danielcosta** [comment]
Yes, this is happening to me too.
I'm here to follow this thread...

**Comment by DivyaArora-24** [comment]
Is there any update on this ? Any help would be appreciated.

**Comment by dsact** [comment]
I'm having the same issue.  updates will be appreciated!

**Comment by javarebel** [comment]
Any updates on this issue?

**Comment by aswinkumarr-hexaware** [comment]
Getting same error

**Comment by KyselMatus** [comment]
same here

**Comment by AdelinaChelcea** [comment]
Getting the same error

**Comment by varunsree** [comment]
I'm having the same issue.  Any updates on this issue?

**Comment by arthurwonggithub** [comment]
Unusable package
