### ISSUE TITLE
Please make sure it is in your tsconfig via the 'files' or 'include' property

### ISSUE THREAD

**Issue by chenchuraviteja** [AmolBorse/angular4-multiselect-dropdown#6]
when i am using this package in angular 6 having below error

> ERROR in ./node_modules/angular4-multiselect-dropdown/angular4-multiselect-dropdown.ts
> Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
> Error: /home/users/praviteja/git-repo/espn/espn-analytics-web/node_modules/angular4-multiselect-dropdown/angular4-multiselect-dropdown.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (/home/users/praviteja/git-repo/espn/espn-analytics-web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:752:23)
>     at plugin.done.then (/home/users/praviteja/git-repo/espn/espn-analytics-web/node_modules/@ngtools/webpack/src/loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by arthurwonggithub** [comment]
I have the same issue_
